import { TOKENS } from './tokens.js'

export const MODULES = {
  dashboard:   { label: 'Overview',     accent: TOKENS.crimson,     icon: 'home' },
  analytics:   { label: 'Analytics',    accent: TOKENS.accentNavy,  icon: 'chart' },
  users:       { label: 'Users',        accent: TOKENS.crimson,     icon: 'users' },
  teachers:    { label: 'Teachers',     accent: TOKENS.accentTeal,  icon: 'teacher' },
  allocations: { label: 'Manage Students',  accent: TOKENS.accentAmber, icon: 'allocations' },
  communication: { label: 'Communication', accent: TOKENS.crimson, icon: 'mail' },
  community:     { label: 'Community',     accent: TOKENS.crimson, icon: 'users' },
  announcements: { label: 'Announcements', accent: TOKENS.crimson, icon: 'mail' },
  frontdesk:   { label: 'Front Desk',   accent: TOKENS.accentAmber, icon: 'frontdesk' },
  payroll:     { label: 'Payroll',      accent: TOKENS.accentEmerald, icon: 'payroll' },
  leave:       { label: 'Leave',        accent: TOKENS.accentSlate, icon: 'leave' },
  programmes:  { label: 'Programmes',   accent: TOKENS.accentPurple, icon: 'programmes' },
  documents:   { label: 'Documents',    accent: TOKENS.gold,        icon: 'documents' },
  assessment:  { label: 'Assessments', accent: TOKENS.accentAmber, icon: 'frontdesk' },
  crm:         { label: 'CRM',         accent: TOKENS.accentNavy,  icon: 'frontdesk' },
  reports:     { label: 'Reports',     accent: TOKENS.crimson,     icon: 'frontdesk' },
  exams:       { label: 'Exams & Assessments', accent: TOKENS.crimson,     icon: 'frontdesk' },
  students:    { label: 'Students',             accent: TOKENS.accentNavy,  icon: 'users' },
  doshomework:  { label: 'Homework',              accent: TOKENS.accentAmber, icon: 'frontdesk' },
  dosanalytics: { label: 'Performance Analytics', accent: TOKENS.crimson,    icon: 'chart' },
  dosattend:    { label: 'Attendance Analytics',   accent: TOKENS.accentTeal,    icon: 'frontdesk' },
  checkin:      { label: 'Check In',              accent: TOKENS.accentEmerald||'#065F46', icon: 'frontdesk' },
  dosbreaks:    { label: 'Staff Breaks',           accent: TOKENS.crimson,       icon: 'frontdesk' },
  sessions:     { label: 'Student Sessions',       accent: TOKENS.accentAmber,   icon: 'users' },
  suggestions:  { label: 'Suggestions',            accent: TOKENS.gold,          icon: 'mail' },
  dostimetable: { label: 'Timetables',             accent: TOKENS.accentNavy, icon: 'rooms' },
  salesperf:   { label: 'My Performance', accent: TOKENS.gold,      icon: 'frontdesk' },
  livelessons: { label: 'Live Classes', accent: TOKENS.accentRose,  icon: 'live' },
  grouprooms:  { label: 'Group Rooms',  accent: TOKENS.accentOcean, icon: 'rooms' },
  curriculum:  { label: 'Curriculum',   accent: TOKENS.gold,        icon: 'curriculum' },
  billing:      { label: 'Billing',          accent: TOKENS.accentEmerald, icon: 'billing' },
  questionbank:   { label: 'Question Bank',   accent: TOKENS.accentAmber,   icon: 'quiz' },
  markingreview:  { label: 'Marking Review',  accent: TOKENS.accentEmerald, icon: 'quiz' },
  feecollection:  { label: 'Fee Collection',   accent: TOKENS.accentEmerald, icon: 'billing' },
  cooreports:     { label: 'Report Overview',  accent: TOKENS.accentAmber,   icon: 'reports' },
  teacherratings: { label: 'Teacher Ratings',  accent: TOKENS.accentAmber,   icon: 'payroll' },
  studio:      { label: 'Studio',       accent: TOKENS.gold,        icon: 'website' },
  website:     { label: 'Website',      accent: TOKENS.accentNavy,  icon: 'website' },
  settings:    { label: 'Settings',     accent: TOKENS.s500,        icon: 'settings' },
  ai:          { label: 'Mshauri AI',   accent: TOKENS.crimson,     icon: 'ai' },
}
